# TCL File Generated by Component Editor 20.1
# Fri Mar 26 12:44:57 EDT 2021
# DO NOT MODIFY


# 
# DDR_Read "DDR_Read" v1.0
# Jared Hermans 2021.03.26.12:44:57
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module DDR_Read
# 
set_module_property DESCRIPTION ""
set_module_property NAME DDR_Read
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Jared Hermans"
set_module_property DISPLAY_NAME DDR_Read
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL DDR3_Read_Top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file DDR3_Read_Top.vhd VHDL PATH ../Source/DDR3_Read_Top.vhd TOP_LEVEL_FILE
add_fileset_file FIFO_IP.vhd VHDL PATH ../Source/FIFO_IP.vhd
add_fileset_file SDRAM_CTRL.vhd VHDL PATH ../Source/SDRAM_CTRL.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL DDR3_Read_Top
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file DDR3_Read_Top.vhd VHDL PATH ../Source/DDR3_Read_Top.vhd
add_fileset_file FIFO_IP.vhd VHDL PATH ../Source/FIFO_IP.vhd
add_fileset_file SDRAM_CTRL.vhd VHDL PATH ../Source/SDRAM_CTRL.vhd


# 
# parameters
# 
add_parameter MASTER_ADDRESSWIDTH INTEGER 30
set_parameter_property MASTER_ADDRESSWIDTH DEFAULT_VALUE 30
set_parameter_property MASTER_ADDRESSWIDTH DISPLAY_NAME MASTER_ADDRESSWIDTH
set_parameter_property MASTER_ADDRESSWIDTH TYPE INTEGER
set_parameter_property MASTER_ADDRESSWIDTH UNITS None
set_parameter_property MASTER_ADDRESSWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MASTER_ADDRESSWIDTH HDL_PARAMETER true
add_parameter SLAVE_ADDRESSWIDTH INTEGER 2
set_parameter_property SLAVE_ADDRESSWIDTH DEFAULT_VALUE 2
set_parameter_property SLAVE_ADDRESSWIDTH DISPLAY_NAME SLAVE_ADDRESSWIDTH
set_parameter_property SLAVE_ADDRESSWIDTH TYPE INTEGER
set_parameter_property SLAVE_ADDRESSWIDTH UNITS None
set_parameter_property SLAVE_ADDRESSWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SLAVE_ADDRESSWIDTH HDL_PARAMETER true
add_parameter MASTER_DATAWIDTH INTEGER 32
set_parameter_property MASTER_DATAWIDTH DEFAULT_VALUE 32
set_parameter_property MASTER_DATAWIDTH DISPLAY_NAME MASTER_DATAWIDTH
set_parameter_property MASTER_DATAWIDTH TYPE INTEGER
set_parameter_property MASTER_DATAWIDTH UNITS None
set_parameter_property MASTER_DATAWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MASTER_DATAWIDTH HDL_PARAMETER true
add_parameter SLAVE_DATAWIDTH INTEGER 32
set_parameter_property SLAVE_DATAWIDTH DEFAULT_VALUE 32
set_parameter_property SLAVE_DATAWIDTH DISPLAY_NAME SLAVE_DATAWIDTH
set_parameter_property SLAVE_DATAWIDTH TYPE INTEGER
set_parameter_property SLAVE_DATAWIDTH UNITS None
set_parameter_property SLAVE_DATAWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SLAVE_DATAWIDTH HDL_PARAMETER true
add_parameter NUMREGS INTEGER 4
set_parameter_property NUMREGS DEFAULT_VALUE 4
set_parameter_property NUMREGS DISPLAY_NAME NUMREGS
set_parameter_property NUMREGS TYPE INTEGER
set_parameter_property NUMREGS UNITS None
set_parameter_property NUMREGS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NUMREGS HDL_PARAMETER true
add_parameter REGWIDTH INTEGER 32
set_parameter_property REGWIDTH DEFAULT_VALUE 32
set_parameter_property REGWIDTH DISPLAY_NAME REGWIDTH
set_parameter_property REGWIDTH TYPE INTEGER
set_parameter_property REGWIDTH UNITS None
set_parameter_property REGWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property REGWIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point SDRAM_Rst_n
# 
add_interface SDRAM_Rst_n reset end
set_interface_property SDRAM_Rst_n associatedClock SDRAM_Clk
set_interface_property SDRAM_Rst_n synchronousEdges DEASSERT
set_interface_property SDRAM_Rst_n ENABLED true
set_interface_property SDRAM_Rst_n EXPORT_OF ""
set_interface_property SDRAM_Rst_n PORT_NAME_MAP ""
set_interface_property SDRAM_Rst_n CMSIS_SVD_VARIABLES ""
set_interface_property SDRAM_Rst_n SVD_ADDRESS_GROUP ""

add_interface_port SDRAM_Rst_n SDRAM_Rst_n reset Input 1


# 
# connection point avalon_slave_control
# 
add_interface avalon_slave_control avalon end
set_interface_property avalon_slave_control addressUnits WORDS
set_interface_property avalon_slave_control associatedClock clock_sink
set_interface_property avalon_slave_control associatedReset reset_sink
set_interface_property avalon_slave_control bitsPerSymbol 8
set_interface_property avalon_slave_control burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_control burstcountUnits WORDS
set_interface_property avalon_slave_control explicitAddressSpan 0
set_interface_property avalon_slave_control holdTime 0
set_interface_property avalon_slave_control linewrapBursts false
set_interface_property avalon_slave_control maximumPendingReadTransactions 0
set_interface_property avalon_slave_control maximumPendingWriteTransactions 0
set_interface_property avalon_slave_control readLatency 0
set_interface_property avalon_slave_control readWaitTime 1
set_interface_property avalon_slave_control setupTime 0
set_interface_property avalon_slave_control timingUnits Cycles
set_interface_property avalon_slave_control writeWaitTime 0
set_interface_property avalon_slave_control ENABLED true
set_interface_property avalon_slave_control EXPORT_OF ""
set_interface_property avalon_slave_control PORT_NAME_MAP ""
set_interface_property avalon_slave_control CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_control SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_control Control_Avalon_MM_Write write Input 1
add_interface_port avalon_slave_control Control_Avalon_MM_WriteData writedata Input slave_datawidth
set_interface_assignment avalon_slave_control embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_control embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_control embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_control embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink Clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock SDRAM_Clk
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink Rst_n reset Input 1


# 
# connection point SDRAM_Clk
# 
add_interface SDRAM_Clk clock end
set_interface_property SDRAM_Clk clockRate 0
set_interface_property SDRAM_Clk ENABLED true
set_interface_property SDRAM_Clk EXPORT_OF ""
set_interface_property SDRAM_Clk PORT_NAME_MAP ""
set_interface_property SDRAM_Clk CMSIS_SVD_VARIABLES ""
set_interface_property SDRAM_Clk SVD_ADDRESS_GROUP ""

add_interface_port SDRAM_Clk SDRAM_Clk clk Input 1


# 
# connection point avalon_master_SDRAM
# 
add_interface avalon_master_SDRAM avalon start
set_interface_property avalon_master_SDRAM addressUnits WORDS
set_interface_property avalon_master_SDRAM associatedClock SDRAM_Clk
set_interface_property avalon_master_SDRAM associatedReset SDRAM_Rst_n
set_interface_property avalon_master_SDRAM bitsPerSymbol 8
set_interface_property avalon_master_SDRAM burstOnBurstBoundariesOnly false
set_interface_property avalon_master_SDRAM burstcountUnits WORDS
set_interface_property avalon_master_SDRAM doStreamReads false
set_interface_property avalon_master_SDRAM doStreamWrites false
set_interface_property avalon_master_SDRAM holdTime 0
set_interface_property avalon_master_SDRAM linewrapBursts false
set_interface_property avalon_master_SDRAM maximumPendingReadTransactions 0
set_interface_property avalon_master_SDRAM maximumPendingWriteTransactions 0
set_interface_property avalon_master_SDRAM readLatency 0
set_interface_property avalon_master_SDRAM readWaitTime 1
set_interface_property avalon_master_SDRAM setupTime 0
set_interface_property avalon_master_SDRAM timingUnits Cycles
set_interface_property avalon_master_SDRAM writeWaitTime 0
set_interface_property avalon_master_SDRAM ENABLED true
set_interface_property avalon_master_SDRAM EXPORT_OF ""
set_interface_property avalon_master_SDRAM PORT_NAME_MAP ""
set_interface_property avalon_master_SDRAM CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_SDRAM SVD_ADDRESS_GROUP ""

add_interface_port avalon_master_SDRAM SDRAM_Avalon_MM_Address address Output master_addresswidth
add_interface_port avalon_master_SDRAM SDRAM_Avalon_MM_WaitReq waitrequest Input 1
add_interface_port avalon_master_SDRAM SDRAM_Avalon_MM_ReadData readdata Input master_datawidth
add_interface_port avalon_master_SDRAM SDRAM_Avalon_MM_Read read Output 1
add_interface_port avalon_master_SDRAM SDRAM_Avalon_MM_BE byteenable Output master_datawidth/8


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end export_q q Output 4*master_datawidth
add_interface_port conduit_end export_rdempty rdempty Output 1
add_interface_port conduit_end export_rdreq rdreq Input 1
add_interface_port conduit_end export_aclr aclr Input 1

